### ISSUE TITLE
Update info app to verify file conforms to GeoModelGrids HDF5 layout

### ISSUE THREAD

**Issue by baagaard-usgs** [baagaard-usgs/geomodelgrids#77]
Update info app to verify that file conforms to GeoModelGrids HDF5 layout, including required attributes and self consistency of data. The resolution of the blocks must be an integer multiple of the resolution of the topography if it is included. The blocks should also fill the model domain.

**Comment by baagaard-usgs** [comment]
## TODO

- [ ] Add `HDF5::hasAttribute()`
- [ ] Verify attributes exist when loading model metadata.
  - [ ] `Modelnfo::load()`
  - [ ] `Model::loadMetadata()`
- [ ] Implement `_Info::verifyTopography()` (topography spans domain).
- [ ] Implement `_Info::verifyBlock()` (blocks span domain, resolution is integer multiple of topography resolution)
