### ISSUE TITLE
Create application to generate Vs isosurface for Z1.0 and Z2.5

### ISSUE THREAD

**Issue by baagaard-usgs** [baagaard-usgs/geomodelgrids#85]
Implementing in branch `feature-isosurface-app`

**Comment by baagaard-usgs** [comment]
Implementing in [feature-isosurface-app](https://github.com/baagaard-usgs/geomodelgrids/tree/feature-isosurface-app)

# Todo

- [ ] Add isosurface values to command line arguments (defaults should be 1.0 and 2.5)
- [ ] Add reference surface to command line arguments
- [ ] Add reference surface to Isosurfacer
- [ ] Check reference surface exists in models
- [ ] Implement Isosurfacer::query()
- [ ] Add LineSearch with quadratic fitting
- [ ] Add LineSearch with linear fitting
